# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- REL-/*

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world! $(release)
  displayName: 'Run a one-line script hi hello'

- script: |
    ech "deploying following release"
    echo  $(release)
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: 'print(''Hello Az DevOps'')'