# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world! $(release)
  displayName: 'Run a one-line script'

- script: |
    ech "deploying following release"
    echo  $(release)
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: 'print(''Hello Az DevOps'')'
    
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    
- task: PowerShell@2
  displayName: List all Folders in $(Pipeline.Workspace) 
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
      Get-ChildItem -path $(Pipeline.Workspace)

- task: Bash@3
  displayName: List all Folders in $(System.DefaultWorkingDirectory)
  inputs:
    targetType: 'inline'
    script: |
      tree $(System.DefaultWorkingDirectory)