apiVersion : apps/v1
kind: Deployment
metadata:
  name: azure-devops 
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: azure-devops 
  template:
    metadata:
      labels:
        app: azure-devops 
    spec:
      containers:
        - name: azure-devops
          image: cwstageregistry.azurecr.io/cw-demo-app
    
