apiVersion : apps/v1
kind: Deployment
metadata:
  name: kmapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kmapp
  template:
    metadata:
      labels:
        app: kmapp 
    spec:
      containers:
        - name: kmapp
          image: azuredevopskm.azurecr.io/kmapp
    
